pi-pulse:
  "10":
    stream: http://192.168.121.10:8001/stream
  "11":
    stream: http://192.168.121.11:8001/stream

sen66:
  "11":
    stream: http://192.168.121.11:8002/stream
    nc-stream: http://192.168.121.11:8002/nc-stream
